<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>HsCardImageExporter</RootNamespace>
    <AssemblyName>HsCardImageExporter</AssemblyName>
    <LangVersion>latest</LangVersion>
    <RepositoryLibRoot>..\..\src\EmberMod\Libs</RepositoryLibRoot>
    <HearthstoneInstallDir Condition="'$(HearthstoneInstallDir)' == ''">C:\Program Files (x86)\Hearthstone</HearthstoneInstallDir>
    <BepInExCoreDir Condition="Exists('$(RepositoryLibRoot)\BepInExCore\BepInEx.dll')">$(RepositoryLibRoot)\BepInExCore</BepInExCoreDir>
    <BepInExCoreDir Condition="'$(BepInExCoreDir)' == ''">$(HearthstoneInstallDir)\BepInEx\core</BepInExCoreDir>
    <HearthstoneManagedDir Condition="Exists('$(RepositoryLibRoot)\LibHearthstone\Assembly-CSharp.dll')">$(RepositoryLibRoot)\LibHearthstone</HearthstoneManagedDir>
    <HearthstoneManagedDir Condition="'$(HearthstoneManagedDir)' == ''">$(HearthstoneInstallDir)\Hearthstone_Data\Managed</HearthstoneManagedDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCoreDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCoreDir)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(HearthstoneManagedDir)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(HearthstoneManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(HearthstoneManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(HearthstoneManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(HearthstoneManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Blizzard.T5.AssetLoader">
      <HintPath>$(HearthstoneManagedDir)\Blizzard.T5.AssetLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Blizzard.T5.AssetManager">
      <HintPath>$(HearthstoneManagedDir)\Blizzard.T5.AssetManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Blizzard.T5.ServiceLocator">
      <HintPath>$(HearthstoneManagedDir)\Blizzard.T5.ServiceLocator.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
