services:
  hearthstone-card-search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hearthstone-card-search
    environment:
      ASPNETCORE_HTTP_PORTS: 5888
      CARD_RESOURCE_ROOT: /data
      FILTER_BAR_CONFIG_ROOT: /config
    ports:
      - "5888:5888"
    volumes:
      - ./:/data:ro
      - ./config:/config
    restart: unless-stopped
